---
abstractspacing: double
appendix: false
fontfamily: libertine
monofont: inconsolata
monofontoptions: scaled=.95
fontsize: 12pt
geometry: 
  - top=0.5cm
  - bottom=0.5cm
  - left=1.5cm
  - right=1.5cm
urlcolor: darkblue
highlight-style: arrow
csl: /home/mathias/Descargas/apa.csl
bibliography: /home/mathias/Descargas/Kinetoplastidos.bib
reference-section-title: "Referencias"
lang: es

format: 
    pdf:
      toc: false
      toc-depth: 2
      number-sections: true
      colorlinks: true
      link-citations: true
      linkcolor: black
      urlcolor: blue
      citecolor: black
      fig-cap-location: top
---

<div style="text-align: left;">
**Mathias**
</div>
<div style="text-align: right;">
26 Octubre, 2025
</div>

# Orígenes evolutivos de familias génicas en parásitos kinetoplástidos

## Introduccion

La historia de la vida está marcada por transiciones en diferentes momentos de la evolucion entre formas de vida libres y parasitarias, cada transicion es acompañada por profundas transformaciones genómicas y fenotípicas [@jacksonKinetoplastidPhylogenomicsReveals2016]. Los parásitos representan una porción significativa de la biodiversidad eucariota, con su aparición se han generado cambios en la evolución y la ecología de prácticamente todos los demás organismos.

El parasitismo no implican únicamente pérdida de genes, sino también reorganización y expansión de ciertos genes. Al depender energéticamente del hospedador, los parásitos pueden enfrentar menos restricciones en cuanto al contenido genomico, lo que posibilita la retención y diversificación de familias génicas asociadas a la interacción hospedador-parásito [@jacksonInsightsGenomeSequence2008].

Los Kinetoplástidos son un grupo de eucariotas que representan un buen modelo para estudiar estos procesos evolutivos, dado que incluye tanto organismos de vida libre (*Bodo saltans, Neobodo designis*) asi como parasitos de gran relevancia médica (*Trypanosoma y Leishmania*) y agrícola (*Phytomonas*) [@opperdoesComparativeMetabolismFreeliving2016; @yazakiGlobalKinetoplasteaPhylogeny2017]. Esta diversidad en un unico grupo permite establecer comparaciones directas a nivel evolutivo sobre ganancia y perdidas de genes [@yazakiGlobalKinetoplasteaPhylogeny2017].

Los genomas de *Trypanosoma brucei*, *Trypanosoma cruzi*, *Leishmania major* y *Pythomonas* tienen una organización genómica compleja, caracterizada por una alta proporción familias génicas implicadas en la interacción con el hospedador, la evasión inmune y la adhesión celular. Entre las familias con mayor representacion se ecuentran trans-sialidasas, mucinas, MASP, amastinas y GP63, con distinto grados de divergencia entre e intra especies [@yurchenkoGenomicsTrypanosomatidaeWhere2021].

El origen evolutivo de estas familias genicas asociadas al estilo de vida parasitario continúa siendo un tema en discusion. Una interrogante clave para entender los procesos evolutivos es determinar si estas familias génicas son innovaciones que surgieron junto con la transición hacia el parasitismo, o si derivan de genes de especies ancestrales preexistentes que posteriormente pudieron diversificarse y expandirse en respuesta a presiones selectivas ambientales como la interacción con el hospedador.

## Objetivos

### Objetivo general

Investigar los diferentes orígenes y la historia evolutiva de familias multigénicas en Kinetoplástidos parásitos, con el fin de identificar patrones de expansión, conservación y diversificacion asociados al parasitismo a traves de la evolucion.

### Objetivos específicos

Identificar las familias génicas conservadas en cada especie parasitaria y aquellas compartidas entre especies parásitas y de vida libre.

Reconstruir las relaciones evolutivas, los patrones de duplicación y pérdida de las familias génicas como las trans-sialidasas, mucinas, MASP, amastinas y GP63.

Analizar la organización genómica y la distribución cromosómica de dichas familias en cada especie.

## Metodologia

### Obtención y preparación de datos genómicos

Los datos genómicos se obtendrán de la base de datos **https://protists.ensembl.org/**, seleccionando a las especies de Kinetoplástidos parásitos (*Trypanosoma cruzi, T. brucei, Leishmania major*) y de vida libre (como *Bodo saltans y Neobodo designis*), ademas se integraran genomas de Euglenozoa (*Euglena gracilis, Diplonema papillatum, Perkinsela spp. y Naegleria gruberi*) abracando organismos ancestrales.

Se descargan los datos genomicos para cada especie, archivos formato FASTA, archivos en formato GFF con las anotaciones y coordenadas. Filtrando en el mismo entorno para incluir únicamente genes anotados como "protein_coding" y excluir elementos hipotéticos.

Posteriormente, los datos se analizaran en un entorno local. Verificando que toda anotacion y formatos esten normalizados en los diferentes genomas, a partir de comandos de bash y comandos de awk. Las anotaciones estandarizadas garantizaran un correcto enlace entre las secuencias y sus metadatos (identificador, posición genómica, longitud, producto génico y tipo de anotación).

### Identificación y clasificación de familias multigénicas

Las anotaciones entre los diferentes genomas varian, ya que son anotados en base a diferentes programas, reanotaremos estas familias multigenicas a partir de un set de secuencias curadas de forma manual. Luego, se realizará una búsqueda basada en homología mediante las herramientas BLAST con sus aplicaciones y getorf. Los genes/proteinas serán agrupadas en familias génicas en base a criterios de similitud.

Para la busqueda de homologos remotos en especies ancestrales se constuiran perfiles de hmm a partir de los alineamientos de proteinas reanotadas. De esta manera identificaremos genes con homologia remota en los ancestros de Kinetoplástidos.

### Análisis filogenético

Los alineamientos de cada familia se haran utilizando mafft, seguidos de la construcción filogenética mediante IQ-TREE con modelos de sustitución, seleccionando el mejor modelo que se ajuste. El arbol de eespecies se reconstruira a partir de uno hecho anteriormente en otro trabajo.

Se inferirán los patrones de duplicación y pérdida génica mediante superposicion en un árboles de especies. Permitiendo identificar eventos de expansión o contracción asociados a la transición hacia el parasitismo.

### Caracterización genómica y distribución cromosómica

Para la caracterización inicial, se utilizará el paquete seqinR de R. Este paquete facilita la manipulación y el análisis de secuencias. Se calcularán para cada gen la longitud de secuencia, contenido de GC (% de guanina y citosina), frecuencias de dinucleótidos y trinucleótidos.

Adicionalmente, se analizarán las secuencias proteicas para determinar la frecuencia de aminoácidos y su clasificación en diferentes grupos fisicoquímicos. Permitiendo identificar qué grupos de aminoácidos están enriquecidos en la familia génica.

Se analizarán las posiciones genómicas de cada familia para evaluar su organización y distribución a lo largo de los cromosomas. Se centrará en el entorno genómico y la localización en regiones subteloméricas y centroméricas. Siendo clasificados en función de la región cromosómica que ocupan.

### Aprendizaje automático

Estos resultados serán almacenados en tablas con las familias génicas y caracteristicas. Posteriormente, los resultados obtenidos se aplicara reducción de dimensionalidad (PCA, t-SNE, UMAP) haciendo uso de la herramienta scikit-learn de python. Con el objetivo de explorar los datos y encontrar posibles patrones que distingan los organismos parasitos de los de vida libre u otro patron global de caracter evolutivo o biologico.

En el caso que se encuentren patrones consistentes, se realizara análisis de clustering sobre estos espacios latentes. Para esto se evaluaran distintos algoritmos, incluyendo k-means, DBSCAN, Agglomerative Clustering y Spectral Clustering, con el objetivo de detectar grupos de familias con caracteristicas compartidas. Se utilizara el paquete de scikit-learn de Python, dado que facilita el uso de todas estas herramientas de forma sencilla.

### Reconstrucción de duplicaciones y pérdidas de genes

Para reconstruir la historia de duplicación y pérdida de cada familia génica utilizaremos GeneRax, un software que implementa un modelo de probabilidad DTL (duplication,transfer,loss) y se basan en un proceso estocástico de nacimiento-muerte (birth-death). Aunque GeneRax utiliza probabilidades de eventos evolutivos, el fundamento del modelo es se puede expresar mediante una ecuacion diferencial simple:

$\frac{dN}{dt} = \lambda N - \mu N$

donde $N(t)$ es el número esperado de copias génicas en el tiempo, $\lambda$ es la tasa de duplicación y $\mu$ la tasa de pérdida. Mostrando cómo el tamaño de una familia génica cambia a lo largo del tiempo entre duplicaciones (nacimiento) y pérdidas (muerte).

En este sentido, GeneRax extiende esta formulación a un marco probabilístico del proceso nacimiento-muerte, modelando la probabilidad de observar k copias. Esta formulación les permite inferir eventos discretos de duplicación y pérdida sobre las ramas del árbol de especies, integrando simultáneamente la verosimilitud del alineamiento y de la reconciliación.

### Desarrollo de un pipeline de trabajo reproducible

Con el objetivo de asegurar el versionado y reproducibilidad de los resultados, se implementará un pipeline automatizado en Nextflow, integrando todas las etapas del análisis (descarga de datos, filtrado, alineamiento, reconstrucción filogenética, cálculos genómicos y análisis multivariante). 

El código y los resultados intermedios serán versionados mediante Git y alojados en un repositorio GitHub público, siguiendo buenas prácticas de reproducibilidad y documentación clara.
